### ISSUE TITLE
FredApi Unsatisfiable requirements in julia-1.5.0 

### ISSUE THREAD

**Issue by proudindiv** [markushhh/FredApi.jl#4]
`add FredApi` fails for julia version 1.5.0

```
(v1.5) pkg> add FredApi
  Resolving package versions...
ERROR: Unsatisfiable requirements detected for package FredApi [1f615318]:
 FredApi [1f615318] log:
 ├─possible versions are: [0.1.0, 0.2.0] or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions [0.1.0, 0.2.0]
 ├─restricted by compatibility requirements with DataFrames [a93c6f00] to versions: 0.2.0 or uninstalled, leaving only versions: 0.2.0
 │ └─DataFrames [a93c6f00] log:
 │   ├─possible versions are: [0.11.7, 0.12.0, 0.13.0-0.13.1, 0.14.0-0.14.1, 0.15.0-0.15.2, 0.16.0, 0.17.0-0.17.1, 0.18.0-0.18.4, 0.19.0-0.19.4, 0.20.0-0.20.2, 0.21.0-0.21.7] or uninstalled
 │   ├─restricted to versions * by an explicit requirement, leaving only versions [0.11.7, 0.12.0, 0.13.0-0.13.1, 0.14.0-0.14.1, 0.15.0-0.15.2, 0.16.0, 0.17.0-0.17.1, 0.18.0-0.18.4, 0.19.0-0.19.4, 0.20.0-0.20.2, 0.21.0-0.21.7]
 │   ├─restricted by compatibility requirements with Tables [bd369af6] to versions: [0.11.7, 0.12.0, 0.13.0-0.13.1, 0.20.1-0.20.2, 0.21.0-0.21.7] or uninstalled, leaving only versions: [0.11.7, 0.12.0, 0.13.0-0.13.1, 0.20.1-0.20.2, 0.21.0-0.21.7]
 │   │ └─Tables [bd369af6] log:
 │   │   ├─possible versions are: [0.1.0-0.1.15, 0.1.17-0.1.19, 0.2.0-0.2.11, 1.0.0-1.0.5] or uninstalled
 │   │   └─restricted to versions 1 by Impute [f7bf1975], leaving only versions 1.0.0-1.0.5
 │   │     └─Impute [f7bf1975] log:
 │   │       ├─possible versions are: 0.5.0 or uninstalled
 │   │       └─Impute [f7bf1975] is fixed to version 0.5.0
 │   └─restricted by compatibility requirements with RDatasets [ce6b1742] to versions: [0.13.0-0.13.1, 0.14.0-0.14.1, 0.15.0-0.15.2, 0.16.0, 0.17.0-0.17.1, 0.18.0-0.18.4, 0.19.0-0.19.4, 0.20.0-0.20.2, 0.21.0-0.21.7], leaving only versions: [0.13.0-0.13.1, 0.20.1-0.20.2, 0.21.0-0.21.7]
 │     └─RDatasets [ce6b1742] log:
 │       ├─possible versions are: [0.5.0, 0.6.0-0.6.10] or uninstalled
 │       ├─restricted to versions * by an explicit requirement, leaving only versions [0.5.0, 0.6.0-0.6.10]
 │       └─restricted by compatibility requirements with DataFrames [a93c6f00] to versions: [0.5.0, 0.6.0-0.6.1, 0.6.6-0.6.10] or uninstalled, leaving only versions: [0.5.0, 0.6.0-0.6.1, 0.6.6-0.6.10]
 │         └─DataFrames [a93c6f00] log: see above
 └─restricted by compatibility requirements with TimeSeries [9e3dc215] to versions: uninstalled — no versions left
   └─TimeSeries [9e3dc215] log:
     ├─possible versions are: [0.13.0, 0.14.0-0.14.1, 0.15.0, 0.16.0-0.16.1, 0.17.0, 0.18.0, 0.19.0-0.19.1] or uninstalled
     ├─restricted to versions * by an explicit requirement, leaving only versions [0.13.0, 0.14.0-0.14.1, 0.15.0, 0.16.0-0.16.1, 0.17.0, 0.18.0, 0.19.0-0.19.1]
     └─restricted by compatibility requirements with Tables [bd369af6] to versions: [0.13.0, 0.14.0-0.14.1, 0.15.0, 0.16.0, 0.17.0, 0.18.0, 0.19.0-0.19.1] or uninstalled, leaving only versions: [0.13.0, 0.14.0-0.14.1, 0.15.0, 0.16.0, 0.17.0, 0.18.0, 0.19.0-0.19.1]
       └─Tables [bd369af6] log: see above

(v1.5) pkg>
```

**Comment by markushhh** [comment]
Thank you for opening the issue!
The log output says there are `unsatisfiable requirements` which is due to the `Project.toml` file restricting other packages to certain versions.
I double checked with my v"1.5.0" installation where it works. This is because there is no package version clash for my environment.
I opened another [issue](https://github.com/markushhh/FredApi.jl/issues/5) since I could need help on improving the `Project.toml` file.
I try to fix the issue in the [dev branch](https://github.com/markushhh/FredApi.jl/tree/dev) if it is due to the limits I've set.

**Comment by markushhh** [comment]
Which versions of `DataFrames`, `Tables`, `RDatasets`, and `TimeSeries` are installed in your environment? You can get the versions with:
```
using Pkg
Pkg.status()
```
This would help me in solving it.

I guess in the short run working with [separate environments](https://julialang.github.io/Pkg.jl/v1/environments/) would solve your issue.

**Comment by proudindiv** [comment]
Here are my versions.  My ubuntu 20.04 system was freshly installed about a week ago to correct
some driver problems that I had been having and a fresh install of julia 1.5.0 with re-adding all the
packages that I use since then. I do the `pkg update` on the julia-1.5.0 several times a day to keep
current.

```
(v1.5) pkg> status DataFrames HTTP JSON RDatasets Tables TimeSeries
Status `/xxxxxxxxxxx/.julia/environments/v1.5/Project.toml`
  [a93c6f00] DataFrames v0.21.7
  [cd3eb016] HTTP v0.8.17
  [682c06a0] JSON v0.21.0
  [ce6b1742] RDatasets v0.6.10
  [bd369af6] Tables v1.0.5
  [9e3dc215] TimeSeries v0.19.1

(v1.5) pkg> 
```

**Comment by markushhh** [comment]
I changed the version bounds in the `Project.toml` in the dev version. On my machine it works for your specified versions. 

Could you please check on the dev version? I'll merge it with the master if it works for you.
`] add FredApi#dev`

**Comment by proudindiv** [comment]
I was able to `add FredApi#dev` and initial simple tests worked.  Thank you.

I wasn't able to get the separate environment to work because I'm using
the IJulia jupyter notebooks and that seems to be a lot more complex.

**Comment by markushhh** [comment]
I thank you for pointing this one out!
Unfortunately i do not really use IJulia but since julia 1.5 (I think) having different environments for every project is the way to go.
AFAIK you'd still have a project and you can still have a separate environment for every one even though you work with IJulia and notebooks.
